export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

export const cities = [
  "Chennai",
  "Coimbatore",
  "Madurai",
  "Tiruchirappalli",
  "Salem",
  "Erode",
  "Vellore",
  "Tirunelveli",
  "Thoothukudi",
  "Dindigul",
  "Karur",
  "Nagapattinam",
  "Nagercoil",
  "Kanchipuram",
  "Cuddalore",
  "Pudukkottai",
  "Villupuram",
  "Tiruvannamalai",
  "Kovai",
  "Chidambaram",
  "Vikramasingapuram",
  "Sivakasi",
  "Ramanathapuram",
  "Perambalur",
  "Ariyalur",
  "Virudhunagar",
  "Krishnagiri",
  "Sivaganga",
  "Tenkasi",
  "Kallakurichi"
];

export const jobs = [
  "Actor/Actress",
  "Accountant",
  "Advisory Consultant",
  "Advertising Executive",
  "Airline Pilot",
  "Analyst",
  "Animal Caretaker",
  "Architect",
  "Art Director",
  "Artist",
  "Athlete",
  "Banker",
  "Barber",
  "Barista",
  "Biomedical Engineer",
  "Broker",
  "Building Manager",
  "Business Analyst",
  "Business Consultant",
  "Business Owner",
  "Carpenter",
  "Chef",
  "Chemical Engineer",
  "Civil Engineer",
  "Cleaner",
  "Clinical Researcher",
  "Consultant",
  "Contractor",
  "Corporate Trainer",
  "Creative Director",
  "Customer Support Specialist",
  "Data Analyst",
  "Data Scientist",
  "Dentist",
  "Designer",
  "Dietitian",
  "Doctor",
  "Driver",
  "Economist",
  "Editor",
  "Electrical Engineer",
  "Electrician",
  "Entrepreneur",
  "Executive Assistant",
  "Fashion Designer",
  "Financial Advisor",
  "Financial Analyst",
  "Fitness Instructor",
  "Freelancer",
  "Geologist",
  "Graphic Designer",
  "Hair Stylist",
  "Human Resources Manager",
  "Industrial Engineer",
  "Insurance Agent",
  "Interior Designer",
  "IT Consultant",
  "IT Specialist",
  "Journalist",
  "Lab Technician",
  "Lawyer",
  "Lecturer",
  "Librarian",
  "Logistics Manager",
  "Machine Learning Engineer",
  "Machinist",
  "Maintenance Technician",
  "Marketing Executive",
  "Marketing Manager",
  "Mechanical Engineer",
  "Nurse",
  "Nutritionist",
  "Operations Manager",
  "Optometrist",
  "Photographer",
  "Physical Therapist",
  "Physician",
  "Pilot",
  "Plumber",
  "Project Manager",
  "Public Relations Specialist",
  "Real Estate Agent",
  "Recruiter",
  "Researcher",
  "Retail Manager",
  "Sales Executive",
  "Sales Manager",
  "Software Developer",
  "Software Engineer",
  "Speech Therapist",
  "Surgeon",
  "Teacher",
  "Technician",
  "Translator",
  "Travel Agent",
  "Truck Driver",
  "Tutor",
  "Veterinarian",
  "Web Developer",
  "Writer",
  "Zookeeper",
  "UX/UI Designer",
  "SEO Specialist",
  "Cloud Engineer",
  "Content Writer",
  "Cybersecurity Specialist",
  "Project Coordinator",
  "Procurement Specialist",
  "Medical Researcher",
  "Mobile App Developer",
  "Real Estate Developer",
  "Construction Manager",
  "Product Manager",
  "Supply Chain Manager",
  "Risk Manager",
  "Patent Attorney",
  "Government Employee",
  "Event Planner",
  "Legal Advisor",
  "Marketing Strategist",
  "Social Media Manager",
  "Product Designer",
  "App Developer",
  "Compliance Officer",
  "Construction Worker",
  "Court Reporter",
  "CFO (Chief Financial Officer)",
  "CMO (Chief Marketing Officer)",
  "COO (Chief Operating Officer)",
  "Chief Executive Officer (CEO)",
  "Chief Technology Officer (CTO)",
  "Counselor",
  "Customer Service Manager",
  "Data Engineer",
  "Development Manager",
  "Diplomat",
  "Electric Vehicle (EV) Technician",
  "Entrepreneur/Start-Up Founder",
  "Event Coordinator",
  "Fitness Coach",
  "Forensic Scientist",
  "Fraud Investigator",
  "Full Stack Developer",
  "Game Designer",
  "Game Developer",
  "Government Contractor",
  "Grants Administrator",
  "Health and Safety Officer",
  "Human Resources Specialist",
  "Import/Export Specialist",
  "Instructional Designer",
  "Insurance Broker",
  "Investment Banker",
  "IT Project Manager",
  "Legal Consultant",
  "Life Coach",
  "Loan Officer",
  "Logistics Coordinator",
  "Market Research Analyst",
  "Mechanical Technician",
  "Mobile Developer",
  "Operations Research Analyst",
  "Pharmacist",
  "Photographer",
  "Pilot (Commercial/Private)",
  "Production Manager",
  "Public Health Specialist",
  "Public Policy Analyst",
  "Purchasing Manager",
  "Quality Assurance Tester",
  "Quantity Surveyor",
  "Real Estate Broker",
  "Research Analyst",
  "Retail Executive",
  "Safety Officer",
  "SAP Consultant",
  "Social Worker",
  "Software Architect",
  "Solar Energy Technician",
  "Tax Consultant",
  "Technical Writer",
  "Telecommunications Engineer",
  "Training Specialist",
  "Translator/Interpreter",
  "Transport Manager",
  "Travel Blogger",
  "User Experience Researcher",
  "Video Producer",
  "Visual Merchandiser",
  "Web Designer",
  "Wine Sommelier",
  "Youth Worker",
  "Zoologist"
];

export const banks = [
  "State Bank of India (SBI)",
  "Punjab National Bank (PNB)",
  "Bank of Baroda (BoB)",
  "Canara Bank",
  "Union Bank of India",
  "Indian Bank",
  "Bank of India (BoI)",
  "Central Bank of India",
  "Indian Overseas Bank (IOB)",
  "UCO Bank",
  "Bank of Maharashtra",
  "Corporation Bank",
  "Vijaya Bank",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "IndusInd Bank",
  "Yes Bank",
  "IDFC First Bank",
  "Federal Bank",
  "RBL Bank (Ratnakar Bank)",
  "South Indian Bank",
  "Karur Vysya Bank",
  "DCB Bank",
  "Bandhan Bank",
  "Lakshmi Vilas Bank",
  "Citibank",
  "Standard Chartered Bank",
  "HSBC",
  "Deutsche Bank",
  "Barclays Bank",
  "BNP Paribas",
  "Bank of America",
  "JPMorgan Chase",
  "Royal Bank of Scotland (RBS)",
  "Tokyo-Mitsubishi UFJ Bank",
  "Andhra Pragathi Grameena Bank",
  "Arunachal Pradesh Rural Bank",
  "Assam Gramin Vikash Bank",
  "Bangiya Gramin Vikash Bank",
  "Baroda Uttar Pradesh Gramin Bank",
  "Chhattisgarh Rajya Gramin Bank",
  "Dakshin Bihar Gramin Bank",
  "Himachal Pradesh Gramin Bank",
  "Jammu & Kashmir Gramin Bank",
  "Karnataka Vikas Gramin Bank",
  "Kerala Gramin Bank",
  "Madhya Bihar Gramin Bank",
  "Maharashtra Gramin Bank",
  "Manipur Rural Bank",
  "Nagaland Rural Bank",
  "Odisha Gramya Bank",
  "Punjab Gramin Bank",
  "Rajasthan Marudhara Gramin Bank",
  "Saurashtra Gramin Bank",
  "Tamil Nadu Gramin Bank",
  "Tripura Gramin Bank",
  "Uttarakhand Gramin Bank",
  "Uttar Bihar Gramin Bank",
  "Uttaranchal Gramin Bank",
  "The Pune District Central Cooperative Bank",
  "The Maharashtra State Co-operative Bank",
  "The Thane District Central Co-operative Bank",
  "The Surat District Co-operative Bank",
  "The Varanasi District Co-operative Bank",
  "NABARD (National Bank for Agriculture and Rural Development)",
  "SIDBI (Small Industries Development Bank of India)",
  "EXIM Bank (Export-Import Bank of India)",
  "NHB (National Housing Bank)",
  "BOM (Bank of Maharashtra)",
  "Axis Bank",
  "ICICI Bank",
  "Bank of India",
  "Canara Bank",
  "UCO Bank",
  "State Bank of Mysore",
  "Bank of Rajasthan",
  "Syndicate Bank",
  "IDBI Bank",
  "Oriental Bank of Commerce",
  "Indian Bank",
  "Andhra Bank",
  "Karur Vysya Bank",
  "Madhya Pradesh Gramin Bank",
  "Uttarakhand State Co-operative Bank",
  "Tripura Gramin Bank",
  "Central Bank of India",
  "NABARD",
  "Dena Bank",
  "Corporation Bank",
  "Punjab National Bank",
  "Jammu and Kashmir Bank"
];